- hosts: localhost
  become: yes
  vars:
    app_dir: /opt/myapp
    venv_dir: /opt/myapp/venv
    python_version: python3
  tasks:
    - name: Ensure required apt packages are installed
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Copy application folder
      copy:
        src: "{{ playbook_dir }}/."
        dest: "{{ app_dir }}/"
        owner: root
        group: root
        mode: preserve
    - name: Copy requirements.txt to project directory
      copy:
        src: requirements.txt   # Relative to the playbook file
        dest: "{{ project_dir }}/requirements.txt"
        

    - name: Create virtual environment
      command: "{{ python_exec }} -m venv {{ venv_path }}"
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: "{{ python_version }} -m venv"

    - name: Run FastAPI with Uvicorn
      shell: |
        source {{ venv_dir }}/bin/activate
        uvicorn app:app --host 0.0.0.0 --port 8080
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash  # Ensures 'source' works if you prefer

