- hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy application folder (with Dockerfile)
      copy:
        src: "{{ playbook_dir }}/."
        dest: /opt/myapp/
        mode: '0755'


    - name: Build Docker image from Dockerfile
      docker_image:
        name: myappimage
        tag: latest
        build:
          path: /opt/myapp/

    - name: Run container from built image
      docker_container:
        name: myapp
        image: myappimage:latest
        state: started
        ports:
          - "8080:8080"
